apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment 
  labels:
    app: master-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-app
  template:
    metadata:
      labels:
        app: master-app
    spec:
      containers:
      - name: master-app
        image: mapreduceimage.azurecr.io/mapreduce/master_image
        command: ['/code/src/master/master']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment 
  labels:
    app: worker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: mapreduceimage.azurecr.io/mapreduce/worker_image
        command: ['/code/src/worker/worker']
---