kind: Pod
apiVersion: v1
metadata:
  name: worker-app
  labels:
    app: worker-app
spec:
  containers:
  - name: worker-app
    image: srics96/worker_image
    command: ./worker

---
kind: Service
apiVersion: v1
metadata:
  name: worker-service
spec:
  selector:
    app: worker-app
  ports:
  # Default port used by the image
  - port: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worker-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/worker"
        backend:
          service:
            name: worker-service
            port:
              number: 5001
---