FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y ca-certificates zookeeper libzookeeper-mt2 zookeeperd zookeeper-bin libzookeeper-mt-dev 
ADD lib /usr/local/lib/
ADD boost/* /usr/lib/x86_64-linux-gnu/
WORKDIR /code
COPY . /code